#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "https://dataiter.readthedocs.io/en/latest/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(href=re.compile("#dataiter\."))):
        name = tag.attrs["href"].strip()
        if not name: continue
        path = root + name
        docsets.insert(db, name, "func", path)
