#!/bin/sh
cd "$(dirname "$0")" || exit 1
wget -N https://developer.gnome.org/glib/stable/api-index-full.html
mv -fv Documents Documents.bak$(date +%s)
mkdir -v Documents
mv -fv api-index-full.html Documents
