#!/bin/sh
set -e
if [ $# -lt 1 ]; then
    echo "Download and index documentation for use."
    echo "Usage: ./$(basename "$0") DIRECTORY..."
    exit 1
fi
for DIRECTORY; do
    echo "Entering $DIRECTORY..."
    cd "$DIRECTORY/Contents/Resources"
    [ -f download ] && ./download
    [ -f index ] && ./index
    cd "../../.."
done
