#!/bin/sh
cd "$(dirname "$0")" || exit 1
wget -N http://www.gnu.org/software/emacs/manual/elisp.html_node.tar.gz
mv -fv Documents Documents.bak$(date +%s)
rm -rf elisp
tar -xvf elisp.html_node.tar.gz
mv -v elisp Documents
rm -fv elisp.html_node.tar.gz
