#!/bin/sh
cd "$(dirname "$0")" || exit 1
wget -N http://www.gnu.org/software/emacs/manual/html_node/elisp/Index.html
mv -fv Documents Documents.bak$(date +%s)
mkdir -v Documents
mv -fv Index.html Documents
