#!/bin/sh
cd "$(dirname "$0")" || exit 1
mv -fv Documents Documents.bak$(date +%s)
rm -rf ss64.com
wget --recursive \
     --convert-links \
     --page-requisites \
     --no-parent \
     http://ss64.com/nt/

mv -fv ss64.com Documents
