#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "https://www.gnu.org/software/bash/manual/html_node/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(href=re.compile("#index-"))):
        name = tag.text.strip()
        if not name: continue
        path = root + tag.attrs["href"].strip()
        docsets.insert(db, name, "func", path)
