#!/bin/sh
cd "$(dirname "$0")" || exit 1
mv -fv Documents Documents.bak$(date +%s)
rm -rf sailfishos.org
wget --recursive \
     --convert-links \
     --page-requisites \
     --no-parent \
     --no-check-certificate \
     https://sailfishos.org/develop/docs/silica/

mv -fv sailfishos.org Documents
# Rename files that have traces of URL parameters.
for X in $(find Documents | grep "?"); do
    Y="$(echo "$X" | sed "s/\?.*$//")"
    mv -fv "$X" "$Y"
done
