#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
added = []
root = "https://sailfishos.org/develop/docs/silica/"
soup = docsets.soup_from_url("https://sailfishos.org/develop/docs/silica/sailfish-silica-all.html")
for tag in soup.find_all("a", dict(href=re.compile("qml-.*html"))):
    name = tag.text.split(":")[0].strip()
    path = root + tag.attrs["href"].strip()
    if not (name, path) in added:
        docsets.insert(db, name, "func", path)
        added.append((name, path))
    soup = docsets.soup_from_url(path)
    for li in soup.find_all("li", class_="fn"):
        attrs = dict(href=re.compile("-(prop|method)$"))
        for tag in li.find_all("a", attrs):
            fullname = ".".join((name, tag.text.strip()))
            fullpath = root + tag.attrs["href"].strip()
            if not (fullname, fullpath) in added:
                docsets.insert(db, fullname, "func", fullpath)
                added.append((fullname, fullpath))
