#!/usr/bin/env python3
import os, re, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
db = docsets.create_database()
root = "https://developer.mozilla.org"
for soup in docsets.soups_from_files("Documents/Index"):
    for tag in soup.find_all("a", dict(href=re.compile("/en-US/docs/Web/JavaScript/Reference/"))):
        name = tag.text.strip()
        if not name: continue
        if " " in name: continue
        path = root + tag.attrs["href"].strip()
        docsets.insert(db, name, "func", path)
