#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "http://leafletjs.com/reference-1.2.0.html"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("tr", dict(id=re.compile("-"))):
        name = tag["id"].strip().replace("-", ".")
        if not name: continue
        if re.search(r"\s", name): continue
        path = root + "#" + tag["id"].strip()
        docsets.insert(db, name, "func", path)
