#!/usr/bin/env python3
import os, re, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
db = docsets.create_database()
root = "http://leafletjs.com/reference.html"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("tr", dict(id=re.compile("-"))):
        name = tag["id"].strip().replace("-", ".")
        if not name: continue
        if re.search(r"\s", name): continue
        path = root + "#" + tag["id"].strip()
        docsets.insert(db, name, "func", path)
