#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "https://docs.djangoproject.com/en/2.1/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.select("dt > a"):
        href = tag.attrs["href"].strip()
        href = re.sub("^../", "", href)
        name = href.split("#")[-1]
        if not name.startswith("django."): continue
        path = root + href
        docsets.insert(db, name, "func", path)
