#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "http://flask.pocoo.org/docs/0.12/api/index.html"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("dt", dict(id=re.compile(r"^flask\."))):
        name = tag.attrs["id"].strip()
        if not name: continue
        path = "#".join((root, name))
        docsets.insert(db, name, "func", path)
