#!/usr/bin/env python3
import importlib.machinery, os
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "https://lazka.github.io/pgi-docs/Gtk-3.0/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.select("a.internal.reference"):
        if not "title" in tag.attrs: continue
        name = tag.attrs["title"].strip()
        href = tag.attrs["href"].strip()
        if href == "#": continue
        path = root + href
        docsets.insert(db, name, "func", path)
