#!/usr/bin/env python3
import os, re, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
db = docsets.create_database()
root = "http://pandas.pydata.org/pandas-docs/stable/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(href=re.compile("generated/"))):
        name = tag.attrs["href"].strip()
        name = name.split("#")[-1]
        if not name: continue
        if name.startswith("module-"):
            name = name.replace("module-", "")
        path = root + tag.attrs["href"].strip()
        docsets.insert(db, name, "func", path)
