#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "http://pandas.pydata.org/pandas-docs/stable/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(href=re.compile("generated/"))):
        name = tag.attrs["href"].strip()
        name = name.split("#")[-1]
        if not name: continue
        if name.startswith("module-"):
            name = name.replace("module-", "")
        path = root + tag.attrs["href"].strip()
        docsets.insert(db, name, "func", path)
