#!/usr/bin/env python3
import os, re, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
db = docsets.create_database()
root = "https://developer.gnome.org/gdk3/stable/"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(href=re.compile("^[^/]+#[^/]+$"))):
        name = tag.text.strip()
        if not name: continue
        path = root + tag.attrs["href"].strip()
        docsets.insert(db, name, "func", path)
