#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "https://nodejs.org/dist/latest-v10.x/docs/api/all.html"
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.select("a.mark"):
        name = tag.parent.parent.text
        if (re.match(r"^class:", name.lower()) or
            re.match(r"^class method:", name.lower()) or
            re.match(r"^class property:", name.lower()) or
            re.match(r"^\w+[._]\w+", name.lower())):
            name = name.rstrip("#")
            name = name.split(":", 1)[-1]
            name = name.split("(")[0]
            name = name.strip()
            path = root + tag.attrs["href"]
            docsets.insert(db, name, "func", path)
