#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
root = "https://developer.mozilla.org"
for soup in docsets.soups_from_files("Documents/Element"):
    for tag in soup.find_all("a", dict(href=re.compile("/en-US/docs/Web/HTML/"))):
        name = tag.text.strip()
        if not name: continue
        if name[0].isupper(): continue
        path = root + tag.attrs["href"].strip()
        docsets.insert(db, name, "func", path)
