#!/bin/sh
cd "$(dirname "$0")" && mkdir -p Documents && cd Documents
wget -N -t2 -T10 https://www.postgresql.org/docs/current/static/bookindex.html
wget -N -t2 -T10 https://www.postgresql.org/docs/current/static/sql-commands.html
