#!/usr/bin/env python3
import os, re, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
db = docsets.create_database()
added = []
root = "https://www.postgresql.org/docs/9.6/static/"
for soup in docsets.soups_from_files("Documents/sql-commands.html"):
    for tag in soup.find_all("a", dict(href=re.compile("^sql-"))):
        name = tag.text.strip()
        name = re.sub(r"\s+", " ", name).strip()
        if not re.search("[A-Z]{2,}", name): continue
        path = root + tag.attrs["href"].strip()
        if not (name, path) in added:
            docsets.insert(db, name, "func", path)
            added.append((name, path))
for soup in docsets.soups_from_files("Documents/bookindex.html"):
    for tag in soup.find_all("a", dict(href=re.compile("^queries-"))):
        name = tag.text.strip()
        name = re.sub(r"\s+", " ", name).strip()
        if not re.search("[A-Z]{2,}", name): continue
        path = root + tag.attrs["href"].strip()
        if not (name, path) in added:
            docsets.insert(db, name, "func", path)
            added.append((name, path))
