#!/usr/bin/env python3
import os, re, sys
os.chdir(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join("..", "..", "..", ".."))
import docsets
db = docsets.create_database()
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(rel=re.compile("bookmark"))):
        name = tag.string
        if " " in name: continue
        path = "http:" + tag["href"]
        docsets.insert(db, name, "func", path)
