#!/usr/bin/env python3
import importlib.machinery, os, re
os.chdir(os.path.dirname(os.path.abspath(__file__)))
docsets = (importlib.machinery.SourceFileLoader(
    "docsets", os.path.join("..", "..", "..", "__init__.py"))
           .load_module("docsets"))
db = docsets.create_database()
for soup in docsets.soups_from_files("Documents/*.html"):
    for tag in soup.find_all("a", dict(rel=re.compile("bookmark"))):
        name = tag.string
        if " " in name: continue
        path = "http:" + tag["href"]
        docsets.insert(db, name, "func", path)
