#!/usr/bin/env python3
import bs4, glob, os, re, sqlite3
os.chdir(os.path.dirname(__file__))
if os.path.isfile("docSet.dsidx"):
    os.remove("docSet.dsidx")
db = sqlite3.connect("docSet.dsidx")
cursor = db.cursor()
cursor.execute("CREATE TABLE searchIndex(id INTEGER PRIMARY KEY, name TEXT, type TEXT, path TEXT);")
cursor.execute("CREATE UNIQUE INDEX anchor ON searchIndex (name, type, path);")
for fname in glob.glob("Documents/index.html"):
    page = open(fname, encoding="utf_8", errors="ignore").read()
    soup = bs4.BeautifulSoup(page)
    for tag in soup.find_all("a", {"rel": re.compile("bookmark")}):
        name = tag.string
        if " " in name: continue
        path = "http:" + tag["href"]
        print("{}: {}".format(name, path))
        cursor.execute("INSERT OR IGNORE INTO searchIndex(name, type, path) VALUES (?,?,?)",
                       (name, "func", path))

db.commit()
db.close()
