#!/bin/sh
cd "$(dirname "$0")" || exit 1
wget -N http://www.gnu.org/software/make/manual/html_node/Name-Index.html
mv -fv Documents Documents.bak$(date +%s)
mkdir -v Documents
mv -fv Name-Index.html Documents
